version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: dcicflix_db
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')"
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5

  calification:
    build: ./calification
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      RABBITMQ_URL: amqp://rabbitmq:5672
      RABBITMQ_EXCHANGE: events_exchange
      RABBITMQ_QUEUE_CLICKS: clicks_queue
      RABBITMQ_QUEUE_CALIFICATIONS: califications_queue
      RABBITMQ_QUEUE_PLAYS: plays_queue
    depends_on:
      rabbitmq:
        condition: service_healthy

  opiniones:
    build: ./opinions
    ports:
      - "3004:3004"
    environment:
      PORT: 3004
      MONGODB_URI: mongodb://mongodb:27017/dcicflix_db
      RABBITMQ_URL: amqp://rabbitmq:5672
      RABBITMQ_EXCHANGE: events_exchange
      RABBITMQ_QUEUE_CLICKS: clicks_queue
      RABBITMQ_QUEUE_CALIFICATIONS: califications_queue
      RABBITMQ_QUEUE_PLAYS: plays_queue
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  recommender:
    build: ./recommender
    ports:
      - "3005:3005"
    environment:
      PORT: 3005
      MONGODB_URI_LOCAL: mongodb://mongodb:27017/dcicflix_db
      MONGODB_URI_ATLAS: mongodb+srv://usuario:password@cluster.mongodb.net/DCICflix?retryWrites=true&w=majority
    depends_on:
      mongodb:
        condition: service_healthy

  api-movies:
    build: ./api-movies
    ports:
      - "3007:3007"
    environment:
      PORT: 3007
      MONGODB_URI: mongodb+srv://admin321:admin123@moviesdb.hsjqo6c.mongodb.net/?appName=MoviesDB
      NODE_ENV: production
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:3007/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  random-movie:
    build: ./random-movie
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      API_MOVIES_URL: http://api-movies:3007/api/movies
    depends_on:
      api-movies:
        condition: service_healthy
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:3001/api/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mongo_data: