version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: dcicflix_db
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')"
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5

  calification:
    build: ./calification
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      RABBITMQ_URL: amqp://rabbitmq:5672
      RABBITMQ_EXCHANGE: events_exchange
      RABBITMQ_QUEUE_CLICKS: clicks_queue
      RABBITMQ_QUEUE_CALIFICATIONS: califications_queue
      RABBITMQ_QUEUE_PLAYS: plays_queue
    depends_on:
      rabbitmq:
        condition: service_healthy

  opiniones:
    build: ./opinions
    ports:
      - "3004:3004"
    environment:
      PORT: 3004
      MONGODB_URI: mongodb://mongodb:27017/dcicflix_db
      RABBITMQ_URL: amqp://rabbitmq:5672
      RABBITMQ_EXCHANGE: events_exchange
      RABBITMQ_QUEUE_CLICKS: clicks_queue
      RABBITMQ_QUEUE_CALIFICATIONS: califications_queue
      RABBITMQ_QUEUE_PLAYS: plays_queue
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  mongo_data: